### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by christianonoh** [smunoz1988/Leaderboard#3]
Reviewed your code and it's excellent! 

Your use of modular code and separation of concerns principle, along with comments and descriptive variable names, make it well-structured and easy to understand. 

One suggestion I have is to improve the user experience by using a darker color for the input boxes or changing the text color to make the values more visible. Overall, great job and I look forward to seeing more of your work!

**Comment by fredo509** [comment]
Hello @smunoz1988  

Good code implementation 💯 
Good Job with the rank implementation 🔢 

<- Optional -> 

You can use an  other color to make your design more attractive &#128521;

**Comment by smunoz1988** [comment]
Thanks for the suggestion. 

Issue close.
